### ISSUE TITLE
Package requires other packages for directories it uses

### ISSUE THREAD

**Issue by davdunc** [davdunc/awscli-2-rpm#45]
> [!]: Package requires other packages for directories it uses.
>      Note: No known owner of /usr/include/aws/common/posix,
>      /usr/lib64/cmake/aws-c-common/shared, /usr/include/aws/testing,
>      /usr/include/aws/common, /usr/lib64/cmake/aws-c-common
> [!]: Package must own all directories that it creates.
>      Note: Directories without known owners: /usr/include/aws/common,
>      /usr/lib64/cmake/aws-c-common, /usr/lib64/cmake/aws-c-common/shared,
>      /usr/include/aws, /usr/include/aws/testing,
>      /usr/include/aws/common/posix

This can be solved by adding the following to the devel subpackage:
```
%dir %{_libdir}/cmake/aws-c-common
%dir %{_libdir}/cmake/aws-c-common/shared
%dir %{_libdir}/include/aws/common
%dir %{_libdir}/include/aws/common/posix
%dir %{_libdir}/include/aws/testing
```

**Comment by kyleknap** [comment]
@davdunc I fixed this issue for `aws-c-common` with this PR: https://github.com/davdunc/awscli-2-rpm/pull/44 but we need to go back and fix this for the rest of the CRT packages as well.

**Comment by davdunc** [comment]
Acknowledged. we can use this to track the others.
